######################## default configuration ####################
baseURL = "https://pleke.com/"
title = "Pleke - Financial Freedom"
theme = "bigspring"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-175589222-1" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true