# main menu
[[main]]
name = "Principal"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "blog"
weight = 2

[[main]]
name = "Perguntas Frequentes"
url = "faq"
weight = 5

# footer menu left
[[footer_left]]
name = "Perguntas Frequentes"
url = "perguntas"

# footer menu middle
[[footer_middle]]
name = "Política de Privacidade"
url = "privacidade"

# footer menu right
[[footer_right]]
name = "Termos e Condições"
url = "termos"
