# main menu
[[main]]
name = "Principal"
url = "/"
weight = 1

[[main]]
name = "Perguntas Frequentes"
url = "perguntas"
weight = 2

# footer menu left
[[footer_left]]
name = "Perguntas Frequentes"
url = "perguntas"

# footer menu middle
[[footer_middle]]
name = "Política de Privacidade"
url = "privacidade"

# footer menu right
[[footer_right]]
name = "Termos de Serviço"
url = "termos"
