# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "blog"
weight = 2

[[main]]
name = "FAQ"
url = "faq"
weight = 5

# footer menu left
[[footer_left]]
name = "FAQ"
url = "faq"

# footer menu middle
[[footer_middle]]
name = "Privacy Policy"
url = "privacy-policy"

# footer menu right
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
