# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "FAQ"
url = "faq"
weight = 2

# footer menu left
[[footer_left]]
name = "FAQ"
url = "faq"

# footer menu middle
[[footer_middle]]
name = "Privacy Policy"
url = "privacy"

# footer menu right
[[footer_right]]
name = "Terms of Service"
url = "terms"
